### ISSUE TITLE
UISpy找不到QPath

### ISSUE THREAD

**Issue by fanlin** [Tencent/QT4i#18]
UISpy显示QPath几乎都是空的，控件查找效率过低，应该怎么切换到wda原生的xpath？ wda原生的inspector功能是被去掉了吗？打不开

**Comment by JerryGinger** [comment]
建议参考[QPath语法](https://qta-tuia.readthedocs.io/zh/latest/qpath.html)编写QPath，若想查看UISpy推荐的QPath，请打开菜单中"显示QPath"。
