### ISSUE TITLE
执行不了 setup.py

### ISSUE THREAD

**Issue by louis-ly** [Tencent/QT4i#2]
/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module __main__ was already imported from setup.py, but /Library/Python/2.7/site-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
qt4i
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by JerryGinger** [comment]
try latest version

**Comment by eeelin** [comment]
麻烦提供一下版本号？
