### ISSUE TITLE
brew tap facebook/fb执行失败

### ISSUE THREAD

**Issue by xyd113** [Tencent/QT4i#22]
https://qt4i.readthedocs.io/zh_CN/latest/intro.html
快速入门的指令：$ brew tap facebook/fb
执行结果：
Cloning into '/usr/local/Homebrew/Library/Taps/fackbook/homebrew-fb'...
Username for 'https://github.com': xxx         
Password for 'https://xxx@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/fackbook/homebrew-fb/' not found
Error: Failure while executing; `git clone https://github.com/fackbook/homebrew-fb /usr/local/Homebrew/Library/Taps/fackbook/homebrew-fb --depth=1` exited with 128.

因为https://github.com/fackbook/homebrew-fb，404

**Comment by JerryGinger** [comment]
最新QT4i不需要安装fbsimctl了
