### ISSUE TITLE
`pip install qt4i` 执行失败

### ISSUE THREAD

**Issue by dinghaoz** [Tencent/QT4i#23]
Collecting qt4i
  Using cached https://files.pythonhosted.org/packages/5f/79/e2d16acbefba57015d35b8a56efd86ae1699328c4cc92ee8bf999aa9f0f8/qt4i-3.4.8.tar.gz
Requirement already satisfied: qtaf>=5.2.9 in ./Library/Python/2.7/lib/python/site-packages (from qt4i) (5.4.30)
Requirement already satisfied: six>=1.11.0 in ./Library/Python/2.7/lib/python/site-packages (from qt4i) (1.12.0)
Collecting pymobiledevice-qta (from qt4i)
  Using cached https://files.pythonhosted.org/packages/02/2b/4d1dae992685390d9002cd69a260c3bf2823038bcc94a161699359a8a60a/pymobiledevice_qta-1.1.4-py2-none-any.whl
Collecting biplist (from qt4i)
  Using cached https://files.pythonhosted.org/packages/3e/56/2db170a498c9c6545cda16e93c2f2ef9302da44802787b45a8a520d01bdb/biplist-1.0.3.tar.gz
Collecting websocket-client (from qt4i)
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Requirement already satisfied: future in ./Library/Python/2.7/lib/python/site-packages (from qt4i) (0.17.1)
Collecting qt4w (from qt4i)
  Using cached https://files.pythonhosted.org/packages/65/d0/2259230f50259038bba5ead3feb636d35c32c0935cb8e3bba9c872388e77/qt4w-2.0.62.tar.gz
Requirement already satisfied: ply in ./Library/Python/2.7/lib/python/site-packages (from qtaf>=5.2.9->qt4i) (3.11)
Collecting M2Crypto==0.32.0; sys_platform == "darwin" (from pymobiledevice-qta->qt4i)
  Using cached https://files.pythonhosted.org/packages/17/2b/f551dbff0f7b70746568c6546efccca128fe8651be7ad915b99e1bae15cf/M2Crypto-0.32.0.tar.gz
Collecting pyasn1 (from pymobiledevice-qta->qt4i)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting construct>=2.9.29 (from pymobiledevice-qta->qt4i)
  Using cached https://files.pythonhosted.org/packages/19/c0/f054941fa33d14378de66d2c0477d31f7ad97aa2e298a5771a7b20bc2039/construct-2.9.45.tar.gz
Requirement already satisfied: typing in ./Library/Python/2.7/lib/python/site-packages (from M2Crypto==0.32.0; sys_platform == "darwin"->pymobiledevice-qta->qt4i) (3.7.4)
Installing collected packages: M2Crypto, pyasn1, construct, biplist, pymobiledevice-qta, websocket-client, qt4w, qt4i
  Running setup.py install for M2Crypto ... error
    ERROR: Complete output from command /usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-install-_9CI3L/M2Crypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-record-_15PGN/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    copying M2Crypto/callback.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/EVP.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/m2.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/EC.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/httpslib.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/X509.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/util.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/DH.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/threading.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/six.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/BN.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/m2crypto.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/Err.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto
    creating build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.macosx-10.14-intel-2.7/M2Crypto/SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build/temp.macosx-10.14-intel-2.7
    creating build/temp.macosx-10.14-intel-2.7/SWIG
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-install-_9CI3L/M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.macosx-10.14-intel-2.7/SWIG/_m2crypto_wrap.o -Wno-deprecated-declarations -DTHREADING
    SWIG/_m2crypto_wrap.c:2887:9: warning: variable 'res' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
        if (PyType_Ready(tp) < 0)
            ^~~~~~~~~~~~~~~~~~~~
    SWIG/_m2crypto_wrap.c:2911:10: note: uninitialized use occurs here
      return res;
             ^~~
    SWIG/_m2crypto_wrap.c:2887:5: note: remove the 'if' if its condition is always false
        if (PyType_Ready(tp) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~
    SWIG/_m2crypto_wrap.c:2868:10: note: initialize the variable 'res' to silence this warning
      int res;
             ^
              = 0
    SWIG/_m2crypto_wrap.c:3557:10: fatal error: 'openssl/err.h' file not found
    #include <openssl/err.h>
             ^~~~~~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-install-_9CI3L/M2Crypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-record-_15PGN/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/4v/k5bkbs8x3j9fkyshtmhx7lqc0000gn/T/pip-install-_9CI3L/M2Crypto/

**Comment by AirChen** [comment]
m2crypto没有安装成功，试试这个方式 https://www.cnblogs.com/fzw-/p/8280900.html

**Comment by JerryGinger** [comment]
参考这里
https://gitlab.com/m2crypto/m2crypto/-/blob/master/INSTALL.rst
